-------------------------------------------------------------------------------------------
--
--  raylib [textures] example - raw data
--
--  This example has been created using raylib 6.0 (www.raylib.com)
--
--  Copyright (c) 2014-2026 Ramon Santamaria (@raysan5)
--
-------------------------------------------------------------------------------------------

local screenWidth, screenHeight = 800, 450
InitWindow(screenWidth, screenHeight, "raylib [textures] example - raw data")

local fudesumiRaw = LoadImageRaw("resources/fudesumi.raw", 384, 512, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0)
local fudesumi = LoadTextureFromImage(fudesumiRaw)
UnloadImage(fudesumiRaw)

-- Checked texture generated in Lua (C example allocated Color pixels with MemAlloc)
local checkedIm = GenImageChecked(960, 480, 32, 32, ORANGE, GOLD)
local checked = LoadTextureFromImage(checkedIm)
UnloadImage(checkedIm)
SetTargetFPS(60)

while not WindowShouldClose() do
    BeginDrawing()
        ClearBackground(RAYWHITE)
        DrawTexture(checked, screenWidth/2 - checked.width/2, screenHeight/2 - checked.height/2, Fade(WHITE, 0.5))
        DrawTexture(fudesumi, 430, -30, WHITE)
        DrawText("CHECKED TEXTURE ", 84, 85, 30, BROWN)
        DrawText("GENERATED by CODE", 72, 148, 30, BROWN)
        DrawText("and RAW IMAGE LOADING", 46, 210, 30, BROWN)
        DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, BROWN)
    EndDrawing()
end
UnloadTexture(fudesumi)
UnloadTexture(checked)
CloseWindow()
